### ISSUE TITLE
jQuery.on() and .off() have several unhandled overloads

### ISSUE THREAD

**Issue by wmadden** [benhowdle89/touche#13]
Their signatures are:

`.on( events [, selector ] [, data ], handler(eventObject) )`
`.off( events [, selector ] [, handler(eventObject) ] )`

but touche.js only handles the trivial case where `events` is a single event name.

Problem cases:
* `events` is a space-separated list of event names, possibly namespaced
* `events` is an *object*, which causes our subsequent `slice()` call to explode

**Comment by idomusha** [comment]
On case 2: 
>Uncaught TypeError: undefined is not a function

Line 66 fails.
```javascript
if (event.slice(0, 5) == 'click')
```
